version: '3'

tasks:
  start:
    desc: Start FHIR server
    cmds:
      - docker-compose up -d
      - echo "FHIR server starting at http://localhost:8080/fhir"
      - echo "Waiting for server to be ready..."
      - sleep 15
      - task: status

  stop:
    desc: Stop FHIR server
    cmds:
      - docker-compose down

  restart:
    desc: Restart FHIR server
    cmds:
      - task: stop
      - task: start

  status:
    desc: Check FHIR server status
    cmds:
      - docker ps --filter "name=fhir-sandbox"
      - echo "Testing metadata endpoint..."
      - 'curl -s -o /dev/null -w "HTTP Status: %{http_code}\n" http://localhost:8080/fhir/metadata || echo "Server not responding"'

  logs:
    desc: View FHIR server logs
    cmds:
      - docker-compose logs -f fhir-sandbox

  test:
    desc: Run all tests
    cmds:
      - mkdir -p tests/results
      - ./tests/test_patient.sh
      - ./tests/test_observation.sh
      - ./tests/test_integration.sh

  test-patient:
    desc: Run Patient tests only
    cmds:
      - mkdir -p tests/results
      - ./tests/test_patient.sh

  test-observation:
    desc: Run Observation tests only
    cmds:
      - mkdir -p tests/results
      - ./tests/test_observation.sh

  test-integration:
    desc: Run integration tests only
    cmds:
      - mkdir -p tests/results
      - ./tests/test_integration.sh

  test-ci:
    desc: Run CI/CD simulation
    cmds:
      - echo "Running CI/CD simulation..."
      - task: start
      - task: test
      - task: stop
      - echo "CI/CD simulation completed successfully!"

  build-multi-arch:
    desc: Build multi-architecture Docker images
    cmds:
      - docker buildx create --name fhir-builder --use --bootstrap || true
      - docker buildx build --platform linux/amd64,linux/arm64 -t fhir-sandbox:latest . || echo "Using compose image"
      - docker buildx rm fhir-builder || true

  clean:
    desc: Clean up containers and volumes
    cmds:
      - docker-compose down -v
      - docker system prune -f

  metadata:
    desc: Fetch FHIR capability statement
    cmds:
      - curl -s http://localhost:8080/fhir/metadata | jq .

  patient:
    desc: Create sample patient
    cmds:
      - |
        curl -X POST http://localhost:8080/fhir/Patient \
          -H "Content-Type: application/fhir+json" \
          -d '{
            "resourceType": "Patient",
            "name": [{"family": "Doe", "given": ["John"]}],
            "gender": "male",
            "birthDate": "1990-01-01"
          }' | jq .